name: Build and Publish Custom Lavalink Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image only if the upstream image has changed
      - name: Build and push Docker image
        run: |
          # Pull the latest base image
          docker pull ghcr.io/lavalink-devs/lavalink:latest

          # Build the custom image with cache invalidation if the base image changes
          docker build --pull --cache-from your-dockerhub-username/lavalink-custom:latest -t your-dockerhub-username/lavalink-custom:latest .

          # Push the image only if it has changed
          docker push your-dockerhub-username/lavalink-custom:latest
